# Generated by Django 4.2.13 on 2024-09-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_balance', models.IntegerField(blank=True, null=True)),
                ('leave_taken', models.IntegerField(blank=True, null=True)),
                ('leave_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100)),
                ('leave_taken_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=150, unique=True)),
                ('number_of_leave_days', models.IntegerField()),
                ('carryover_unused', models.BooleanField()),
                ('employee_leave', models.ManyToManyField(related_name='employee_leaves', through='leave.EmployeeLeave', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_taken', models.IntegerField(blank=True, null=True)),
                ('employee_note', models.TextField()),
                ('leave_request_date', models.DateTimeField(auto_now_add=True)),
                ('acting_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acting_employee', to='employee.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.employeeleave')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_supervisor', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_comment', models.TextField(blank=True, null=True)),
                ('leave_request_status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=100)),
                ('leave_approved_date', models.DateTimeField(auto_now_add=True)),
                ('leave_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approved_employee', to='employee.employee')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leaverequest')),
                ('leave_requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requested_employee', to='employee.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employeeleave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeleave',
            unique_together={('leave_type', 'employee')},
        ),
    ]
