# Generated by Django 4.2.13 on 2024-09-14 13:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('employee_dob', models.DateField(blank=True, default=datetime.datetime.now)),
                ('place_of_birth', models.CharField(max_length=150)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='media/profile_picture')),
                ('home_town', models.CharField(max_length=150)),
                ('date_joined', models.DateField(auto_now=True)),
                ('office_department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.officedepartment')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='employee.employee')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=150)),
                ('education_level', models.CharField(choices=[('doctorate degree', 'Doctorate Degree'), ('masters degree', 'Masters Degree'), ('bachelors degree', 'Bachelors Degree'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='certificate', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('probation_start', models.DateField(blank=True, default=datetime.datetime.now)),
                ('probation_end', models.DateField(blank=True, default=datetime.datetime.now)),
                ('type_of_employement', models.CharField(choices=[('hire', 'Hire'), ('contract', 'Contract')], default='Hire', max_length=100)),
                ('type_of_commitment', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], default='Full Time', max_length=100)),
                ('contract_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=100)),
                ('date_created', models.DateField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.employeetitle')),
            ],
        ),
    ]
